### ISSUE TITLE
Stile scaricabile da Josm

### ISSUE THREAD

**Issue by sabas** [osmItalia/cai_josm_preset#5]
Bisognerebbe pubblicarlo sul sito di josm per renderlo accessibile direttamente dalla applicazione

https://josm.openstreetmap.de/wiki/Presets#Createnewpresets

**Comment by lucadelu** [comment]
Si appena arriviamo ad una versione più o meno stabile lo pubblicheremo

**Comment by lucadelu** [comment]
Una volta pubblicato diffondere la notizia tipo su OSM Wochennotiz / Weekly News

**Comment by sabas** [comment]
Posso inserire io la notizia quando me lo dite.

**Comment by lucadelu** [comment]
Penso sia arrivato il momento di pubblicarlo, che soluzione usiamo? direttamente il link così come in [questa pagina](https://josm.openstreetmap.de/wiki/PresetsSource) o con il metodo suggerito come migliore ?

**Comment by lucadelu** [comment]
Preset [aggiunto](https://josm.openstreetmap.de/wiki/PresetsSource?sfp_email=&sfph_mail=&action=diff&version=81&old_version=80&sfp_email=&sfph_mail=)  e scaricabile da Josm
