### ISSUE TITLE
Cartellonistica ibrida hiking/mtb

### ISSUE THREAD

**Issue by Dardy87** [osmItalia/cai_josm_preset#9]
Sarebbe utile inserire nel preset dei luoghi di posa la spunta per indicare se le indicazioni riguardano anche le mtb oltre che i percorsi a piedi.
Mi sono imbattuto in cartellonistica specifica (https://westnordost.de/p/35435.jpg) con indicazioni sia per pedoni che mtb.
Il fatto di avere questa informazione, al di là della distanza o tempi di percorrenza, dà un'importante informazione che un sentiero sia espressamente dichiarato come ciclabile (cosa non scontata per la maggio parte dei sentieri).
la spunta, facoltativa, dovrebbe comandare il tag mtb=yes

![image](https://user-images.githubusercontent.com/4279340/116143149-1082fa80-a6db-11eb-8e76-82df34bbf866.png)

**Comment by lucadelu** [comment]
ho aggiornato il preset, se va bene puoi chiudere la issue

**Comment by Dardy87** [comment]
Ciao, ho provato ad aggiornare il preset da josm ma sembra ci sia qualcosa che non va

![image](https://user-images.githubusercontent.com/4279340/119823376-07ad6080-bef5-11eb-82d3-dd65cd9ac1fd.png)

La riga in errore sembra proprio quella relativa alla nuova voce mtb.
` <key key="mtb" text="Mountain bike"/>`

Non conosco bene quale sia il problema ma dando un occhio un occhio al file xml a mio avviso andrebbe messo nello stesso modo della checkbox riferita all'emergency:

` <check key="access_point" text="emergency" />`

![image](https://user-images.githubusercontent.com/4279340/119824556-527ba800-bef6-11eb-92e1-93b117a32913.png)

In questo modo si potrebbe variare tra i valori yes,no e non impostato. Se riesco a capire dove josm scarica i i preset locali (se li scarica) posso provare a fare delle prove sul mio pc.

**Comment by lucadelu** [comment]
dovrei aver sistemato...

**Comment by Dardy87** [comment]
Si confermo, ora è ok, grazie.
